apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: moderation
data:
  POSTGRES_DB: moderation
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
  DEBUG: "True"
  CSRF_TRUSTED_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
