apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: moderation
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DJANGO_SECRET_KEY: local-development-secret
